name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check for existing release
        run: |
          # Check whether version contains SNAPSHOT
          grep "^version" gradle.properties | grep -q SNAPSHOT || {
            # Extract version from gradle.properties
            VERSION=$(grep "^version" gradle.properties | sed 's|^version=\(.*\)$|\1|g')
            echo "Query for version [$VERSION]"
            curl --head -L --silent --output /dev/null --fail "$ART_URL/$VERSION" &&  {
              echo "ERROR: Binary arithmetic already exit for version [$VERSION]"
              echo "ERROR: Blocking publishing same version to the Besu Artiactory"
              echo "url $ART_URL/$VERSION"
              exit 1
            }
          }
        env:
          ART_URL: 'https://hyperledger.jfrog.io/artifactory/besu-maven/org/hyperledger/besu/arithmetic'
        
      - name: Publish
        run: echo Publish to Artifactory      



