name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Check for existing release
        run: |
          # Check whether version contains SNAPSHOT
          grep "^version" gradle.properties | grep -q SNAPSHOT || {
            echo "Not a SNAPSHOT"
            # Extract version from gradle.properties
            VERSION=$(grep "^version" gradle.properties | sed 's|^version=\(.*\)$|\1|g')
            echo VERSION=$VERSION
            curl --head -L --silent --output /dev/null --fail "$ART_URL/$VERSION" &&  {
              echo "ERROR: Found binary exist for the version [$VERSION]. Please check the version in gradle.properties"
              echo "url $ART_URL/$VERSION"
              exit 1
            }         
          }
        env:
          ART_URL: 'https://hyperledger.jfrog.io/artifactory/besu-maven/org/hyperledger/besu'
        
      - name: Publish
        run: echo Publish to Artifactory      



